language: ruby
cache: bundler
rvm:
- 2.7.0
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - GIT_NAME=jeffmur
  - GIT_EMAIL=jeffmur@uw.edu
branches:
  only:
  - main
deploy:
  provider: pages
  edge: true # opt in for dp1 v2
  cleanup: true 
  github_token: $GIT_TOKEN 
  commit_message: Deploy %[project_name]
  fqdn: jeffmur.dev