language: ruby
cache: bundler
rvm:
- 2.7.0
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
branches:
  only:
  - main
deploy:
  provider: pages
  edge: true # opt in for dp1 v2
  cleanup: true 
  token: $GITHUB_TOKEN 
  commit_message: Deploy %[project_name]
  fqdn: jeffmur.dev