sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - secure: YBuaghEtFdLyvm60z4Hy76uH5wIVLvlsxWYne2+i7jsUkLCAPSgSTpzNeWlHdyFDFWTJHnIbwX+ZZ98Wno9ph5dpXhTdm21AMejgUjm7TejzrJR24BSLqM5pAq8B+kisLpI1j/Xcye8C+9fWsr8Dddnsi/xKY11eJvf7whNiRtDcVU+CnaPvRKENIr/pkk1IUsFMnOrsRvBsgdvsnJFzGuGlQ2xYciZTPrcd010bkD/GFFLj81fegQhMtBUIFuxjqQDQ3krcYoqNXVxj8iVwIqgj2gADvasOXfPVZBR/ma9il72bstl9PD12CxNiIev2VfxyE+vkXCL9OYCy/pnfs5ff2do4+O6Olrv66d5h8idXcf4Gg1jU08t10+ofSunZZ+/tuYNB0ZPzaEHhkUcYA3c27RlVq2JkXhRkb/0tCUNQCNFn9+HUbpzAMRfTfp0wJ/0yT5WXZwf21RgZ2uitCpf8yUN2tvxGw5oOk2Xh9ZMKJoHR8xPvCV88fHtK07XmbFiCnjjOscY5flyNdHFE6EVbOr6SmZf4pZK0LfRjNM+xoaB0AqtvkHCZv3oLTpvS51/9r+JTD8wIURt6el/PUsNWxlfqDMBxmhtFC4jzc0nnZDR4nwwm2H6o9Kjrx43FWwL4vIFDMtco/ZK61lkZxqd7uIIBaznSppzc/kSGVDI=
branches:
  only:
  - main
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/grunt-cli/bin/grunt release
