sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - GIT_NAME="jeffmur"
  - GIT_EMAIL="jeffmur@uw.edu"
  - secure: "BfwC8265U226wvO40RPnVMeH5vXTfd+WJ/8pi23giVGgJKMQNBmRAep6cxRdCrFy9UVwW1IhKACxG8c8b/GqjABBdhSUOX8BEuH3qtO8iRrbfgHwMTIT8ztLLsWzLNC+mTYSFdypC0zIzf1Tdyu2IsyZA6lsePyypw8P3KOce7+Clgr+GvGeKAxhvpDbpoV8w6K7GhjscjfYHu4HBTFvLUWZuFTYLZFMEo/1cMqX4yPKnQ89bHEENbsr99NVsRl4zdSKPw3jSybCtcLi1Lp+SzaXVUWRqzHMDCk8bZxYm4eOJGixeaP4Vfnb93FqN9grlk7G4jW1dKgDv1OO+uWrIzgx9YLSy8ck6VrWP+rzZ/zTD8hW5wW/x9vchObMVd31So4uNWEvr0mmk6Ekmh8iaxTZ1aTfaZeANF3DDjVsw0+obOaqt+JKy6qxqsjeokvlTXnh2xBRdgBXhp1btVCtXSaKNo/NPCI07X8PgGAtf6VS24N3l950vYMmBIdQ7DRRRJ/UyQjnke7crPFHz81A6LEuZKY5MU5JI1aOf9QK77xD6DdmjruaiIfUxS6tjb0bkaZRXfIgplQMyP0V0OwSZLe+U8LuUiEiS1tw1h6d7h7VDW/4OkuSDvdv9mPNDmgcFccqXbhBYHRa0xKO4v1zeTmvcDvH2uaj1u43ASTp1jg="
  branches:
  only:
  - main
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
