sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - GIT_NAME=jeffmur
  - GIT_EMAIL=jeffmur@uw.edu
  - secure: atnXp7N4Ah2BfxUWnxd2y3uLVMc2L4JWxybV5MjNp05cjfnOLwyfXrUkg9rgkHM9C74M3m4A01cSz9c1A/q7yUyGp0uRT/6MeylLjW5Y8FcmAXxwSZ1w4B2vk3/0KOZqB1dSQ70UhvRi6ZS5u0SeLZkcYd//RkdZgw1+VmVK1o+qEe2MuJwJn/UUeTjJ3Btj97iBYDAOQ9cVkvlf1r0/Jl7nRv1BqQuhGe8xRaaj4w3G8kV/saen0FW7Px0YX162eHxXWxhAPtrEkkTbVCizQXtfM/V15qCmtG331d4z7kEwzlqA5zkt4TiZjqUfr7iIrK81tYtYVdqXMvooYlMccsU6ekNzzJwRRcpkHPThokL2Dh7Yj8sNu0o6xJtlR/aPx4tCJEAJPluGyvwBV0+Du6czABifiHra4QIdDr1gGAYVqrOkfx+n3psJIj64tNE2XdKazly3XCfLK+3lS7slhlnaRabAUfGhWsY32A/kGTd5mkqdb1xv4o2/oZwPGScWnPmCwmBn0wS8QK22zaHt2XLa1nQVy94GUyE/x1OzxWqdNuSQD85a7Z3Thy4i3ZhlgodrykFmvNObFYY2YfYIL0TzhAcq+HUMnHh5naF0EguUxU8iqjcqmC6CuI4yXfyirV6FBqOW/27NHiDBrJv5ABmuUNrFjkJxZzJkhOfjkJs=
branches:
  only:
  - main
  notifications:
    email: false
    slack:
      secure: JxJAbItwTDs4CvlMs5umGOvRW/oqZFgSXmz9acRCSJ1i0dRJAszbqg2KjT6oWPGMjphc56BFIrjZSjqE14tRrUx1dSMH/bgwX4//UfkrjxUsKsyj+BWVa8uijwk4/gWa9MpMWMqPSJITGKYs9OefSYaggvTitY9PkdKJORU3buLCSMVM+AFUGXOc66QXnD+7S3duqG5z/bI+7T15glqCyuQTJLVuu4ULQ/zQr7QqhAvJe+PzKqia6kQGakZyFTb/79PiDRwM2IibuvwJmmQGPzEHPAUpE5txtNfh017G+Pl+LoV7btn2BZYW6XzJF1YauqPt/OdgUPLNhV2tuAUPU1rLaKn+f52PqSukLtihQDZ7s11nc+CmRtwBG0eLNK4pLUmKixnlj4YT/kKbCkhiNQ1dESqep5/7zt4x8/YqeQVZnANzKD1zjSaQjWhU+IF82y/gPqgKSQaK0vu9lhru0XZ0o1Lr0pHQ+UEJu6PAbxCq9U5+XHFEiYnkJjwZAGWE3bYavTzs+0bF/hOVILdqlfltF+RrYsbsuJoN+EBKfIppX2fCm1u84Pw5MXteGaw2IpaKc7y3Y+N6wNHgqD0gHa0jjGMy9qOCz7FrSi4AetzrW4PIg2o2jI2X+WJYQffZEWo0yIrttkUc9xKKt3Qa4Nyq+ViHCaimSHSKZ0SK2Jo=
