sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - GIT_NAME="jeffmur"
  - GIT_EMAIL="jeffmur@uw.edu"
  secure: "pXG4s0vS/OwxQUwtXdmNHyb2KP1X46fpVhavUXJ+WiiSYnb9SSrJXQAj9OyL8EKMG5fY1LQFwG933QxhEryctl+v3maa7zrDfHF8UHiOi3GFV2KiuPPsiDK/Ssj8Gea76tl54Pin4XqB1t8dtPBpDVTYXZDFIv6w+PGWOMkXws8siB/DjUYQJSHy3mOyhdB9kcWjMHRkPfpVeOjSgs2NbXWK1PqbNz4S39WXk0yZG4/yEywxj8Qags5iAvz+f8K3fFoUg70qS3V/4e71Rtucwg3aGgxNJG5VHSbfE/Ao/imr4sk5yu6FEw0BPfpZEZywxQvo/uAVJ43YpVg0J3TMv6C8DIFnzph9aOF0XjMd+6OnAbYfsgyHZr6HD6HHvajxeH2wPhRNbXOwfj2nj7rBLs3z/W2tem+psi+BG7UbEXl3KGyt6goGkBqp6QYwLhZ704D21g74TFKvam985KR6ik/5xixYZzrmCD4SYCN0jc6+/co7ZQPqQ1W5L8Ugr088ouvqgQhlpBIs/3oIhJaOgVs1KPX5MwgbcdHY6dCu4Gkq3tsz5I0gCQoYNwiplbnH3fAQUQ5zdzshiPNNiEzDvNYgtibwWm3afvWqndSdvjpcANw4fSZ9ByQVIDsJ0TXMl2EJzWqoxm/THg7Wee5YubS9pEajIPlli1lF7vxqhIc="
  branches:
  only:
  - main
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
