sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - GIT_NAME="jeffmur"
  - GIT_EMAIL="jeffmur@uw.edu"
    - secure: AMe/Uy8D9NM+wD4jtt9Y08bCfbS5832xSvfFm5t9kmJpDeF6GPRGtS7turobie+IxPVzDLPX86B++HMbXAO5x9JIqCBp48gUUUVaEZzg8Zk1kMarnQpE+YLjTdYUfoRts123ZREpO9EURnVkoVsYLgkUbDhjFkBlhf3LPVTboDXS+N97zUtVCKnNU2otCuxsKpo59zgnMBn/dEKpccusrBuaUI2yNW9YrXPIsZcD04GKEO4BqgeU3B60SRjjvzmdLsilItsW5RELMrHVrf8Y0Yzjxi6cm6sMnEKN5zCzK7RmbTNEu8NFh0nGsujewoQOjqWtLfekA8voq4iCaoPrIiBGiFSL7sRbm7hR3OfpeNhQG+BdTsm6Y/KwORk2hNi4pioLPAWkEOYSM2DuvgogI3ghIIPebCqm7Hi6ie4DhhhV8/w+gyvQdsUksKYfVqXGVIUMczsRUvZsXN41YdC60ivqwd7qR36Tx3eIpYLHJrZyJ/xOE7fMUYJsTUbzzhpz2sG8Jn2zVkPILeDC1jeXJZhKTBCdWktDzOPoYRy/GGVoVe80vjCRLqHfsart5xRQmm+yfYrQOVYc/x8G4WFddzHfbzmiCGxCutVCqbG9xiLQdklne0r3+tkUtZSfsCCO4IUNzbSDsTXIbJnku9YgyZ9AirrpKnC4w+Z+oHowd4o=
branches:
  only:
  - main
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
