sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - GIT_NAME="jeffmur"
  - GIT_EMAIL="jeffmur@uw.edu"
  - secure: Jwm6U+xrkjiy+gMSwdCAKSpJrpOl9usr6Hyg6IByyJqhAMQ/t9hFiLbo5EKslYxhaqBw3oK+VABlVqYKTpHyXj40VwI29Wlv3INlHYurVVJvsSDfLtHjVJs+aUjmvpXhY84fuXON+IumY7980/r0/hlS6K2Drd9Tvwg0ZQI+HzAuF53GY4JCm0MkQFNvBPS5fvblrM7Htp7Ob3DyQIKYSR1vN9vys4Mgc6j0wPWHWORDgUrhR1aLtRd1OUmt05t5+yqQJCwDHVR4+Kuu3kLGV+J6ZPaVgVniMUKtiApkOasfxu+CS3fUDQW7PgoVWCH0f5lim6cOOwGBVMJDXuOwfO81GdlDby7gDx8RkFFQsKJIkQqr9utU7CWBf5gGS98w72QlaI0qa97qyiyQPq11NTRl0hrqbZDGbJR7K++k9Z+yNDmAjh7eEpau0IkgTREGg/CH9iBB5azJG3yAwmfyOgJJcmIOWmB3DhBaag9IGNHAB7fFdaFFOBqYljGZjjdkG6NsBO/wuY9yNYsp9lokNum33KK82m7xdgGSFgNTkQycIaUiHcODQt5T5UyhdR3VyBExHkHDmpnDkK+lLd8Gtmj79YASqzMlaeqIy7OZV6diUuEe+8BYuVq4NlDIGrQezrqVVE8KHLXEQkANAyxd0o7XehTSqP4mtSqkoO6AQ+M=
  - secure: hLJVEUdyi8b4Cy1KL+3UbWn2vsP5pvNuMrmIoRso2vLzwTAeunHT9yszSPwCnF37mVKBBjC2fFde3FJJSu/2nXoqL3XAnRFfOca6byM5vHg5AN0stbqwKwWMYsXeRmN7DX3wr0WaJx8J+WssXl/sfxwJXau2SCZC+dF5XSA3h00xCSg16ic5rcU5ouIOg4yKuQQJI1TjfKsbqstld1JEF30fs9mRUrH6Yg2HuLAJumLmGTaCrw7hqlBvbtUYVKsNMw/4xkgHW9mVyVUvXzIDXWUSloGYMrPfmpYUQhWLIFdV2X1IKocSKLsxVgudfHecXUOzRVI0jj3xKMmhxndVR+/MtKY6ahzZG8tDUcXTqmeJ0qXd7jiO3BEAqIS9Kcemu3NFHrBT98bMdL3gxysiu5a7nFroCYGhofUewrl2dYlQ16Uodfl0snvZ6d9fEzxg0h5yoDmFnlMEEwwf0pLdVGuMZ0i4kYvdxbGZth232RQfzfgT2Py0VgUP8+5jJfz+RINswHM77i9E4x000DKiDYC3QJLiesx1X6axf3fYxnMeG51bepHuRwSGNvJYZSjHUCBSkDltwoumhD57aB++B858lwNoSzw3zjYuKu84QIvSdom2nAEr5YZMiazdmIVYlaX6IcRaTew7gcxU857B1Luwobmb2opF+0/24VN55KA=
branches:
  only:
  - main
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
