sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
  - GIT_NAME="jeffmur"
  - GIT_EMAIL="jeffmur@uw.edu"
branches: 
  only:
  - main
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
deploy:
  token:
    secure: UzUQrLmU2nvmidii0zUiZ+bKCJ8gTnMRgko4o37aYDEVA+RrV93cl6EryqQV6ZxXR8XZ4QrS4ELZsXOiOJlBkVAyoWg7A9AX9wfS6456i2eRbZr1xwi7ldhF4Y2+lK6pCazMmTHjQYpJmqKmgU/LEvkDSl2XeHkAWSDvRyGcO3KzWlucxhl6ZPq2Q71ctYXHrdg7XrgYwLJFTOJSmzED5VuDrzIqAxeLXM/62j6DmNvLxMkn6Wab1LcNAQ+yBfnagDwMjHTcx8Z3CJYRr9X5mdph+iETSOoISpv/AbH2+9/tzwQ5wBxfP/JUZZXA8tOtrBSzlQoUlHVJUVNZUpPiHW1dlGKdY+Yi4xiXNEXUyuE7LOz1fh51+TBKfbVBgrfazVtgOkz2o3ZpVOCZ4Sw+8z9ZIyYxf9aYMzGHkBhr4HG133UTAu9Okj8K1KGqw3LsEAsND6R0MEOjoqwNUQMSgGv9wujJn35uPCNSnvNHOwlYHH5Dgbdzpl1yrZ+ZVhCD3E+IhYdCC00yXuEcXAk2hF7oezOXhPZK10YfmfXbACgeubXSF3FjUzG0Y4aViFgDohr3GBOFRcZDvi2KjV741rVQfPUi53lljaOx3mq/1K7xeSHPpLS7gGAupaZQpIrHyRfDR5zlebp6fJKgF/Nh8JJjPzqSWZ/Ezg78UJEzzV0=
